<a href="https://colab.research.google.com/github/Bayu142002/Basic-Python-Programming-for-Data-Science./blob/main/TUGAS_BAG_6_PER_1_PSDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Membuat Array Menggunakan Numpy


In [31]:
import numpy as np

# Vector
x = np.array([2,3,5,7,9,11])
print("\nvektor bilangan prima\n",x)
y = np.arange(1,20,3)
print("\nvektor 1 sampai 20 dengan beda 3\n",y)

# Linspace
z = np.linspace(1,10,15)
print("\nmembuat linspace\n",z)

# Matrik
a = np.array([(1,3,5),(2,4,6),(1,5,9)])
print("\nmatriks biasa dengan 3 baris dan 3 colom",a)
b = np.zeros((3,2))
print("\nmembuat matriks 3 baris 2 colom yang semua elemennya 0\n",b)
c = np.ones((4,5))
print("\nmembuat matriks 4 baris 5 colom yang semua elemennya 1\n",c)
d = np.identity(8)
print("\nmembuat matriks diagonal, dengan baris 8 colom 8\n",d)
e = np.eye(3)
print("\nmembuat matriks diagonal, dengan baris 3 colom 3\n",e)


vektor bilangan prima
 [ 2  3  5  7  9 11]

vektor 1 sampai 20 dengan beda 3
 [ 1  4  7 10 13 16 19]

membuat linspace
 [ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]

matriks biasa dengan 3 baris dan 3 colom [[1 3 5]
 [2 4 6]
 [1 5 9]]

membuat matriks 3 baris 2 colom yang semua elemennya 0
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

membuat matriks 4 baris 5 colom yang semua elemennya 1
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

membuat matriks diagonal, dengan baris 8 colom 8
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

membuat matriks diagonal, dengan baris 3 colom 3
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##Vektor Dengan Nummpy Array

In [36]:
X = np.array([1,2,4,5,7,8])
print(X)

Y = np.arange(1,24,4)
print(Y) 

[1 2 4 5 7 8]
[ 1  5  9 13 17 21]


##Operasi Vektor

In [37]:
# Penjumlahan
X+Y

array([ 2,  7, 13, 18, 24, 29])

In [38]:
# Pengurangan
X-Y

array([  0,  -3,  -5,  -8, -10, -13])

In [39]:
# Perkalian skalar
X*Y

array([  1,  10,  36,  65, 119, 168])

##Matriks Dengan Numppy Array

In [82]:
A = np.array([(1,2,3),(5,6,7),(9,10,11)])
print("\nMatriks A\n",A)

B = np.array([(1,4,6),(2,4,7),(5,6,1)])
print("\nMatriks B\n",B)

C = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
print("\nMatriks C\n",C)


Matriks A
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

Matriks B
 [[1 4 6]
 [2 4 7]
 [5 6 1]]

Matriks C
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


##Operasi Matriks

In [72]:
# Penjumlahan
np.add(A,B)

array([[ 2,  6,  9],
       [ 7, 10, 14],
       [14, 16, 12]])

In [73]:
# Pengurangan
np.subtract(B,A)

array([[  0,   2,   3],
       [ -3,  -2,   0],
       [ -4,  -4, -10]])

In [59]:
# Perkalian Skalar
7*B

array([[ 7, 28, 42],
       [14, 28, 49],
       [35, 42,  7]])

In [60]:
# Perkalian Matriks
np.multiply(A,B)

array([[ 1,  8, 18],
       [10, 24, 49],
       [45, 60, 11]])

##Dot Product dan Cross Product

In [61]:
# Dot Product
np.dot(A,B)

array([[ 20,  30,  23],
       [ 52,  86,  79],
       [ 84, 142, 135]])

In [56]:
# Cross Product
np.cross(A,B)

array([[  0,  -3,   2],
       [ 14, -21,   8],
       [-56,  46,   4]])

## Aljabar Linier Dengan Numpy

In [70]:
# Inverse
invA = np.linalg.inv(A)
print(invA,"\n")

invB = np.linalg.inv(B)
print(invB)

[[ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-1.12589991e+15  2.25179981e+15 -1.12589991e+15]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]] 

[[-0.82608696  0.69565217  0.08695652]
 [ 0.7173913  -0.63043478  0.10869565]
 [-0.17391304  0.30434783 -0.08695652]]


In [84]:
# Determinan
detA = np.linalg.det(A)
print("Determinan Matriks A = ",detA,"\n")

detB = np.linalg.det(B)
print("Determinan Matriks B = ",detB)

Determinan Matriks A =  -7.105427357600985e-15 

Determinan Matriks B =  46.0


In [85]:
#Mengambil Elemen Diagonal
diaA = np.diag(A)
print(diaA,"\n")

diaB = np.diag(B)
print(diaB,"\n")

diaC = np.diag(C)
print(diaC)

[ 1  6 11] 

[1 4 1] 

[ 1  6 11 16]


In [91]:
#Solve Persamaan Linier
solve1 = np.linalg.solve(B,A)
print(solve1,"\n")

solve2 = np.dot(invB,A)
print(solve2,"\n")

solve3 = np.linalg.solve(A,B)
print(solve3,"\n")

solve4 = np.dot(invA,B)
print(solve4)

[[ 3.43478261  3.39130435  3.34782609]
 [-1.45652174 -1.26086957 -1.06521739]
 [ 0.56521739  0.60869565  0.65217391]] 

[[ 3.43478261  3.39130435  3.34782609]
 [-1.45652174 -1.26086957 -1.06521739]
 [ 0.56521739  0.60869565  0.65217391]] 

[[ 1.12589991e+15  1.12589991e+15 -3.94064967e+15]
 [-2.25179981e+15 -2.25179981e+15  7.88129935e+15]
 [ 1.12589991e+15  1.12589991e+15 -3.94064967e+15]] 

[[ 1.12589991e+15  1.12589991e+15 -3.94064967e+15]
 [-2.25179981e+15 -2.25179981e+15  7.88129935e+15]
 [ 1.12589991e+15  1.12589991e+15 -3.94064967e+15]]


##Principal Component Analysis dengan Numpy

In [92]:
import matplotlib.pyplot as plt
